sources:
  - name: DEV_DBT
    schema: RAW_ANALYTICS

    tables:
      - name: hosts
        identifier: src_hosts

      - name: listings
        identifier: src_listings

      - name: reviews
        identifier: src_reviews

